# .github/workflows/action.yml
name: Setup Environment
description: "Installs OS, Python, Poetry, and Nox.  Configures Git for repository access"

inputs:
  python-version:
    description: "The version of Python to install"
    required: false
    default: "3.10"

  poetry-version:
    description: "The version of Poetry to install"
    required: false
    default: "1.6.0"

  github-token:
    description: "GitHub access token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      run: |
        pip install --constraint=.github/workflows/constraints.txt pip
        pip --version

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Setup local virtual environment
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project false --local

    - name: Install Nox
      uses: excitedleigh/setup-nox@v2.1.0

    - name: Install poetry-nox
      run: pip install nox-poetry

    - name: Install package
      run: |
        poetry install

    - name: Configure git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
