name: "Build Documentation"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_run:
    workflows: ["Tests", "Labeler"]
    types:
      - completed
jobs:
  tests:
    runs-on: "ubuntu-latest"
    env:
      PYTHON_VERS: "3.10"
      POETRY_VERS: "1.6.0"
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
    permissions:
      contents: write
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.1.7
      #
      #      - name: Configure Git
      #        run: |
      #          git config --global user.name "${{ github.actor }}"
      #          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ env.PYTHON_VERS }}
          poetry-version: ${{ env.POETRY_VERS }}

      - name: Build the Documentation
        if: ${{ success() }}
        run: nox -P ${{ env.PYTHON_VERS }} -s docs-build

      - name: 'Trigger "Read the Docs" Build'
        if: ${{ success() }}
        run: |
          curl -X POST https://readthedocs.org/api/v2/webhook/compchem-toolkit/279213/ \
          -d "token=${{ env.READTHEDOCS_TOKEN }}"
