name: Dependabot CI

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        poetry: ["1.6.0"]
    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
    permissions:
      contents: write
    if: |-
      ${{
        github.actor == 'dependabot[bot]' &&
        github.event.workflow_run.conclusion == 'success' &&
        matrix.os == 'ubuntu-latest' &&
        matrix.python == '3.10'
      }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.7

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python }}
          poetry-version: ${{ matrix.poetry }}

      # Add a step to auto-merge Dependabot PRs after tests pass
      - name: Auto-merge Dependabot PR
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
