name: Labeler

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, edited, reopened]
  workflow_run:
    workflows: ["Tests"]
    types: [completed, requested]

jobs:
  label:
    runs-on: "ubuntu-latest"
    env:
      PYTHON_VERS: "3.10"
      POETRY_VERS: "1.6.0"
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.1.7

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ env.PYTHON_VERS }}
          poetry-version: ${{ env.POETRY_VERS }}

      - name: Auto Labeler
        uses: actions/labeler@v4.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Labels
        uses: actions/upload-artifact@v4.4.0
        with:
          name: labels
          path: ./.github/labels.json # Specify your labels file
