name: Labeler

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      label_action:
        description: "Action to perform (e.g., label, unlabel)"
        required: true
        default: "label"
      label_name:
        description: "Name of the label to apply/remove"
        required: false

jobs:
  label:
    name: Run Labeler
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Labeler
        uses: actions/labeler@v3
        with:
          configuration-path: .github/labeler.yml
          action: ${{ github.event.inputs.label_action }}
          name: ${{ github.event.inputs.label_name }}
