name: Labeler

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  label:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        poetry: ["1.6.0"]
    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
    permissions:
      contents: write
    if: |-
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        matrix.os == 'ubuntu-latest' &&
        matrix.python == '3.10'
      }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.1.7

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python }}
          poetry-version: ${{ matrix.poetry }}

      - name: Auto Labeler
        uses: actions/labeler@v4.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Labels
        uses: actions/upload-artifact@v4.4.0
        with:
          name: labels
          path: ./.github/labels.json # Specify your labels file
