name: Release

on:
  workflow_run:
    workflows: ["Tests", "Labeler", "Build Documentation"]
    types:
      - completed

jobs:
  bump-minor-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        poetry: ["1.6.0"]
    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
    permissions:
      contents: write
    if: |-
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        matrix.os == 'ubuntu-latest' &&
        matrix.python == '3.10' &&
        github.ref == 'refs/heads/main'
      }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.7

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python }}
          poetry-version: ${{ matrix.poetry }}

      - name: Bump Minor Version
        if: ${{ success() && matrix.python == '3.10' && matrix.os == 'ubuntu-latest' }}
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nox -P ${{ matrix.python }} -s bump-version -- -- minor

      - name: Trigger Read the Docs build (minor version)
        run: |
          curl -X POST https://readthedocs.org/api/v2/webhook/compchem-toolkit/279213/ \
          -d "token=${{ secrets.READTHEDOCS_TOKEN }}"
