name: Release

on:
  workflow_run:
    workflows: ["Labeler"]
    types:
      - completed

jobs:
  bump_version_readthedocs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Bump version and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          nox -s bump-version -- --automatic
      - name: Trigger Read the Docs build
        env:
          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
        run: |
          curl -X POST https://readthedocs.org/api/v2/webhook/compchem-toolkit/279213/ \
          -d "token=${{ env.READTHEDOCS_TOKEN }}"

  minor_version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: bump_version_readthedocs
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Bump minor version and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          nox -s bump-version -- --minor
      - name: Trigger Read the Docs build (minor version)
        env:
          READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
        run: |
          curl -X POST https://readthedocs.org/api/v2/webhook/compchem-toolkit/279213/ \
          -d "token=${{ env.READTHEDOCS_TOKEN }}"
