name: Release

on:
  merge_group:
  workflow_run:
    workflows: ["Tests", "Labeler", "Build Documentation"]
    types:
      - completed

jobs:
  bump-minor-version:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    env:
      PYTHON_VERS: "3.10"
      POETRY_VERS: "1.6.0"
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.1.7

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ env.PYTHON_VERS }}
          poetry-version: ${{ env.POETRY_VERS }}

      - name: Bump Minor Version
        if: success()
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nox -P ${{ matrix.python }} -s bump-version -- -- minor

      - name: 'Trigger "Read the Docs" Build (minor version update)'
        run: |
          curl -X POST https://readthedocs.org/api/v2/webhook/compchem-toolkit/279213/ \
          -d "token=${{ secrets.READTHEDOCS_TOKEN }}"
